name: Unit Testing Gate

on: pull_request

env:
  NODE_VER: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VER }} 

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test

