# This will eventually become a composite action 
# that should shepherd code to and possibly from a client

on:
  release:
    types: [published]

env:
  CLIENT_REPO: todd-miller/simple_proj
  CLIENT_BRANCH: main
  LANDI_REPO: li-argonauts/simple_proj
  LANDI_BRANCH: main
  LANDI_TO_CLIENT_BRANCH: lia_v0.0.1
  CLIENT_TO_LANDI_BRANCH: todd-miller_main 

jobs:
  curry_to_client:
    runs-on: ubuntu-latest
    if: github.repository == 'li-argonauts/simple_proj' 
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Push to Remote
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: ${{ github.ref }} 
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ env.CLIENT_REPO }}

      - name: Open PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ github.ref }} 
          destination_branch: ${{ github.ref }}
          destination_repository: ${{ env.CLIENT_REPO }}
          pr_title: Release - ${{ github.ref }} 
          pr_body: |
            # First PR From Landi-Argonauts
            
            - need to get other meta like:
              - date
              - author
              - sem-ver
          pr_label: 'RELEASE'

 #  curry_to_landi:
 #    runs-on: ubuntu-latest
 #    if: github.repository == 'todd-miller/simple_proj' 
 #    steps:
 #      - name: checkout
 #        uses: actions/checkout@v2
 #        with:
 #          persist-credentials: false
 #          fetch-depth: 0

 #      - name: Push to Remote
 #        uses: ad-m/github-push-action@master
 #        with:
 #          force: true
 #          branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          repository: ${{ env.LANDI_REPO }}

 #      - name: Open PR
 #        uses: repo-sync/pull-request@v2
 #        with:
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          source_branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          destination_branch: ${{ env.LANDI_BRANCH }}
 #          destination_repository: ${{ env.LANDI_REPO }}
 #          pr_title: First PR From CLIENT! 
 #          pr_body: |
 #            # FIRST PR - from CLIENT! 
 #          pr_label: 'UPDATE_WITH_MAIN'
 # 
