# This will eventually become a composite action 
# that should shepherd code to and possibly from a client

name: COURIER

on:
  release:
    types: [published]

env:
  CLIENT_REPO: todd-miller/simple_proj
  CLIENT_BRANCH: development 
  LANDI_REPO: li-argonauts/simple_proj
  LANDI_BRANCH: main
  LANDI_TO_CLIENT_BRANCH: release
  CLIENT_TO_LANDI_BRANCH: todd-miller_main 

jobs:
  landi-2-client:
    runs-on: ubuntu-latest
    if: github.repository == 'li-argonauts/simple_proj' 
    steps:
      - name: CHECKOUT 
        uses: actions/checkout@v2
        with:
          ref: development
          persist-credentials: false
          fetch-depth: 0
 
      - name: CHANGE_LOG
        id: change-log 
        run: |
          tag=$(git tag --sort=-committerdate | head -1)
          prev=$(git tag --sort=-committerdate | head -2 | tail -1)
          log=$(git log --oneline ${secondTag}..${firstTag})
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "prev=${prev}" >> $GITHUB_OUTPUT
          echo "log=${log}" >> $GITHUB_OUTPUT

      - name: ECHO THINGS
        run: |
          echo ${{github.ref}}
          echo ${{github.sha}}
          echo ${{steps.change-log.outputs.tag}}
          echo ${{steps.change-log.outputs.prev}}
          echo ${{steps.change-log.outputs.log}}

      - name: PUSH TAG TO REMOTE 
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: "refs/tags/${{steps.change-log.outputs.tag}}"
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ env.CLIENT_REPO }}

      - name: PUSH BRANCH REMOTE 
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: "refs/heads/${{steps.change-log.outputs.tag}}"
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ env.CLIENT_REPO }}

      - name: OPEN PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: "refs/heads/${{ steps.change-log.outputs.tag }}"
          destination_branch: ${{ env.CLIENT_BRANCH }}
          destination_repository: ${{ env.CLIENT_REPO }}
          pr_title: Release - ${{ steps.change-log.outputs.tag }} 
          pr_body: |
            # First PR From Landi-Argonauts
             
            - current: ${{ steps.change-log.outputs.tag }} 
            - prev: ${{ steps.change-log.outputs.prev}} 
            ${{ steps.change-log.outputs.log}} 

          pr_label: 'LANDI-RELEASE'

 #  curry_to_landi:
 #    runs-on: ubuntu-latest
 #    if: github.repository == 'todd-miller/simple_proj' 
 #    steps:
 #      - name: checkout
 #        uses: actions/checkout@v2
 #        with:
 #          persist-credentials: false
 #          fetch-depth: 0

 #      - name: Push to Remote
 #        uses: ad-m/github-push-action@master
 #        with:
 #          force: true
 #          branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          repository: ${{ env.LANDI_REPO }}

 #      - name: Open PR
 #        uses: repo-sync/pull-request@v2
 #        with:
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          source_branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          destination_branch: ${{ env.LANDI_BRANCH }}
 #          destination_repository: ${{ env.LANDI_REPO }}
 #          pr_title: First PR From CLIENT! 
 #          pr_body: |
 #            # FIRST PR - from CLIENT! 
 #          pr_label: 'UPDATE_WITH_MAIN'
 # 
