# This will eventually become a composite action 
# that should shepherd code to and possibly from a client

name: COURIER

on:
  release:
    types: [published]

env:
  CLIENT_REPO: todd-miller/simple_proj
  CLIENT_BRANCH: development 
  LANDI_REPO: li-argonauts/simple_proj
  LANDI_BRANCH: main
  LANDI_TO_CLIENT_BRANCH: release
  CLIENT_TO_LANDI_BRANCH: todd-miller_main 

jobs:
  landi-2-client:
    runs-on: ubuntu-latest
    if: github.repository == 'li-argonauts/simple_proj' 
    steps:
      - name: CHECKOUT 
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.sha }}
      
      - name: PREVIOUS TAG
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: previous-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CHANGE_LOG
        id: commit-log
        run: |
          firstTag=$(git tag --sort=-committerdate | head -1)
          secondTag=$(git tag --sort=-committerdate | head -2 | tail -1)
          log=$(git log ${secondTag}..${firstTag} --oneline)
          echo "$firstTag"
          echo "$secondTag"
          echo "$log"
          echo "COMMIT_LOG<<EOF" >> $GITHUB_OUTPUT
          echo "--------------" >> $GITHUB_OUTPUT
          echo "$log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: ECHO THINGS
        run: |
          echo ${{github.ref}}
          echo ${{github.sha}}
          echo ${{steps.previous-tag.outputs.tag}}
          echo ${{steps.commit-log.outputs.COMMIT_LOG}}

      - name: PUSH TAG TO REMOTE 
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: "refs/tags/${{steps.previous-tag.outputs.tag}}"
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ env.CLIENT_REPO }}

      - name: PUSH BRANCH REMOTE 
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: "refs/heads/${{steps.previous-tag.outputs.tag}}"
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ env.CLIENT_REPO }}

      - name: OPEN PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: "refs/heads/${{ steps.previous-tag.outputs.tag }}"
          destination_branch: ${{ env.CLIENT_BRANCH }}
          destination_repository: ${{ env.CLIENT_REPO }}
          pr_title: Release - ${{ steps.previous-tag.outputs.tag }} 
          pr_body: |
            # First PR From Landi-Argonauts
             
             - need to get other meta like:
              - date
              - author
              - ${{ steps.previous-tag.outputs.tag }} 
          pr_label: 'LANDI-RELEASE'

 #  curry_to_landi:
 #    runs-on: ubuntu-latest
 #    if: github.repository == 'todd-miller/simple_proj' 
 #    steps:
 #      - name: checkout
 #        uses: actions/checkout@v2
 #        with:
 #          persist-credentials: false
 #          fetch-depth: 0

 #      - name: Push to Remote
 #        uses: ad-m/github-push-action@master
 #        with:
 #          force: true
 #          branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          repository: ${{ env.LANDI_REPO }}

 #      - name: Open PR
 #        uses: repo-sync/pull-request@v2
 #        with:
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          source_branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          destination_branch: ${{ env.LANDI_BRANCH }}
 #          destination_repository: ${{ env.LANDI_REPO }}
 #          pr_title: First PR From CLIENT! 
 #          pr_body: |
 #            # FIRST PR - from CLIENT! 
 #          pr_label: 'UPDATE_WITH_MAIN'
 # 
