name: COURIER

on:
  release:
    types: [published]

env:
  CLIENT_REPO: todd-miller/simple_proj
  CLIENT_BRANCH: development 
  LANDI_REPO: li-argonauts/simple_proj
  LANDI_BRANCH: main
  LANDI_TO_CLIENT_BRANCH: release
  CLIENT_TO_LANDI_BRANCH: todd-miller_main 

jobs:

  change-log:
    runs-on: ubuntu-latest
    outputs:
      compare_log: ${{steps.version-parser.outputs.compare_log}}
      latest_tag: ${{steps.version-parser.outputs.latest_tag}}
      latest_major: ${{steps.version-parser.outputs.latest_major}}
      latest_minor: ${{steps.version-parser.outputs.latest_minor}}
      latest_patch: ${{steps.version-parser.outputs.latest_patch}}
      prev_version: ${{steps.version-parser.outputs.prev_version}}
      prev_major: ${{steps.version-parser.outputs.prev_major}}
      prev_minor: ${{steps.version-parser.outputs.prev_minor}}
      prev_patch: ${{steps.version-parser.outputs.prev_patch}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
          fetch-depth: 0

      - name: VERSION-PARSER
        id: version-parser
        uses: li-argonauts/gha-tag-parser@v0.4.0

  landi:
    runs-on: ubuntu-latest
    if: github.repository == 'li-argonauts/simple_proj' 
    needs: change-log 
    steps:
      - name: CHECKOUT 
        uses: actions/checkout@v2
        with:
          ref: development
          persist-credentials: false
 
      - name: ECHO THINGS
        run: |
          echo ${{github.ref}}
          echo ${{github.sha}}
          echo ${{needs.change-log.outputs.latest_tag}}
          echo ${{needs.change-log.outputs.prev_tag}}

      - name: CREATE RELEASE BRANCH
        uses: ad-m/github-push-action@master
        if: ${{ needs.change-log.outputs.is_patch == 0 }}
        with:
          force: true
          branch: "refs/heads/release/${{needs.change-log.outputs.latest_major}}.${{needs.change-log.outputs.latest_minor}}.x"
          github_token: ${{ secrets.ACCESS_TOKEN }}

  landi-2-client:
    runs-on: ubuntu-latest
    if: github.repository == 'li-argonauts/simple_proj' 
    needs: change-log
    steps:
      - name: CHECKOUT 
        uses: actions/checkout@v2
        with:
          ref: development
          persist-credentials: false
 
      - name: PUSH TAG TO REMOTE 
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: "refs/tags/${{needs.change-log.outputs.latest_tag}}"
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ env.CLIENT_REPO }}

      - name: PUSH BRANCH REMOTE 
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: "refs/heads/${{needs.change-log.outputs.latest_tag}}"
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ env.CLIENT_REPO }}

      - name: OPEN PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: "refs/heads/${{ needs.change-log.outputs.latest_tag }}"
          destination_branch: ${{ env.CLIENT_BRANCH }}
          destination_repository: ${{ env.CLIENT_REPO }}
          pr_title: "LI Release: ${{ needs.change-log.outputs.latest_tag }}" 
          pr_body: |
            # LI Release: ${{ needs.change-log.outputs.latest_tag }} 
            
            Changes in this Release:

            ${{ needs.change-log.outputs.compare_log}} 

            **Full Changelog**: ${{ needs.change-log.outputs.compare_url }} 
          pr_label: 'LI-RELEASE'
      
 #  curry_to_landi:
 #    runs-on: ubuntu-latest
 #    if: github.repository == 'todd-miller/simple_proj' 
 #    steps:
 #      - name: checkout
 #        uses: actions/checkout@v2
 #        with:
 #          persist-credentials: false
 #          fetch-depth: 0

 #      - name: Push to Remote
 #        uses: ad-m/github-push-action@master
 #        with:
 #          force: true
 #          branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          repository: ${{ env.LANDI_REPO }}

 #      - name: Open PR
 #        uses: repo-sync/pull-request@v2
 #        with:
 #          github_token: ${{ secrets.ACCESS_TOKEN }}
 #          source_branch: ${{ env.CLIENT_TO_LANDI_BRANCH }} 
 #          destination_branch: ${{ env.LANDI_BRANCH }}
 #          destination_repository: ${{ env.LANDI_REPO }}
 #          pr_title: First PR From CLIENT! 
 #          pr_body: |
 #            # FIRST PR - from CLIENT! 
 #          pr_label: 'UPDATE_WITH_MAIN'
 # 
