# Used to tease out new action flows 
on: push

env:
  CLIENT_REPO: todd-miller/simple_proj
  CLIENT_BRANCH: main
  LANDI_REPO: li-argonauts/simple_proj
  LANDI_BRANCH: main
  LANDI_TO_CLIENT_BRANCH: lia_v0.0.1
  CLIENT_TO_LANDI_BRANCH: todd-miller_main 

jobs:
  debugger:
    runs-on: ubuntu-latest
    if: github.repository == 'li-argonauts/simple_proj' 
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: development

      - name: get last commit SHA
        id: commit-sha
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: check sha
        run: echo ${{ steps.commit-sha.outputs.sha_short }}

      - name: get last tag-name
        id: last-tag
        run: |
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "TAG=$tag" >> $GITHUB_ENV

      # create pre-release
      - name: log commits from last tag
        id: log-commits
        run: |
          log=$(git log ${{env.TAG}}..HEAD --oneline)
          echo "${{env.TAG}}"
          echo "$log"  
