# This will eventually become a composite action 
# that should shepherd code to and possibly from a client

on:
  pull_request_target:
    branches:
      - 'release/**'

jobs:
  releaser:
    runs-on: ubuntu-latest
    if: github.repository == 'li-argonauts/simple_proj' 
    steps:
      - name: Checkout Development Branch 
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
            
      - name: Open PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          destination_branch: development 
          pr_title: Update Development w/ Release Patch (For Release x.y.z --> x.y.z+1) 
          pr_body: |
            # Release Patch 
            
            need to:
              - get release target semver
              - patch uptick semver
              - pr body from hotfix --> release
              - draft a new release!

          pr_label: 'HOTFIX'


