# This will eventually become a composite action 
# that should shepherd code to and possibly from a client
name: PATCHER

on:
  pull_request:
    branches:
      - 'release/**'
    types:
      - closed

jobs:
  patcher:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: CHANGE_LOG
        id: change-log 
        run: |
          all_tags=$(git tag --sort=-committerdate)
          tag=$(git tag --sort=-committerdate | head -1)
          echo "all_tags<<EOF" >> $GITHUB_OUTPUT
          echo "$all_tags" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: ECHO Stuff! 
        run: |
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF
          echo ${{github.ref}}
          echo ${{github.sha}}
          echo ${{steps.change-log.outputs.tag}}
          echo ${{steps.change-log.outputs.all_tags}}

      - name: Create Tag on Branch
        run: |
          tag=$(git tag --sort=-committerdate)
          echo "$tag"

      - name: Open PR
        if: startsWith(github.base_ref, 'release/')
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ github.head_ref }}
          destination_branch: development 
          pr_title: Update Development w/ Release Patch (For Release x.y.z --> x.y.z+1) 
          pr_body: |
            # Release Patch 
            
            need to:
              - get release target semver
              - patch uptick semver
              - pr body from hotfix --> release
              - draft a new release!

          pr_label: 'HOTFIX'


