# This will eventually become a composite action 
# that should shepherd code to and possibly from a client
name: PATCHER

on:
  pull_request:
    types:
      - opened

jobs:
  patcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Echo Base and Head Refs
        run: |
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF

      - name: Open PR
        if: startsWith(github.base_ref, 'release/')
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ github.head_ref }}
          destination_branch: development 
          pr_title: Update Development w/ Release Patch (For Release x.y.z --> x.y.z+1) 
          pr_body: |
            # Release Patch 
            
            need to:
              - get release target semver
              - patch uptick semver
              - pr body from hotfix --> release
              - draft a new release!

          pr_label: 'HOTFIX'


