# This will eventually become a composite action 
# that should shepherd code to and possibly from a client
name: RELEASER

on:
  push:
    tags:
      - '*.*.*' 

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          ref: development
          fetch-depth: 0
          persist-credentials: false
      
      - name: CHANGE_LOG
        id: change-log 
        run: |
          tag=$(git tag --sort=-committerdate | head -1)
          prev=$(git tag --sort=-committerdate | head -2 | tail -1)
          log=$(git log ${prev}..${tag} --oneline)

          tag_version=$(echo $tag | grep -o '[^-]*$')
          tag_major=$(echo $tag_version | cut -d. -f1)
          tag_minor=$(echo $tag_version | cut -d. -f2)
          tag_patch=$(echo $tag_version | cut -d. -f3)
          
          prev_version=$(echo $prev | grep -o '[^-]*$')
          prev_major=$(echo $prev_version | cut -d. -f1)
          prev_minor=$(echo $prev_version | cut -d. -f2)
          prev_patch=$(echo $prev_version | cut -d. -f3)

          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "prev=$prev" >> $GITHUB_OUTPUT
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "is_patch=$tag_major == $prev_major && $tag_minor == $prev_minor ))" >> $GITHUB_OUTPUT
          echo "tag_major=$tag_major" >> $GITHUB_OUTPUT
          echo "tag_minor=$tag_minor" >> $GITHUB_OUTPUT
      
      - name: ECHO THINGS
        run: |
          echo ${{github.ref}}
          echo ${{github.sha}}
          echo ${{steps.change-log.outputs.tag}}
          echo ${{steps.change-log.outputs.prev}}
          echo ${{steps.change-log.outputs.version_change}}

      - name: Create Branch
        if: ${{ github.repository == 'li-argonauts/simple_proj' }} 
        run: echo "need to create a branch -> release/${{ steps.change-log.outputs.tag_major}}.${{steps.change-log.outputs.tag.minor}}.x"

      - name: Create Release
        if: ${{ steps.change-log.outputs.is_patch == 1 && github.repository == 'li-argonauts/simple_proj'}} 
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN}}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes in this Release:
              ${{ steps.change-log.outputs.log}}
          draft: true 

