# This will eventually become a composite action 
# that should shepherd code to and possibly from a client
name: RELEASER

on:
  push:
    tags:
      - '*.*.*' 

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: CHANGE_LOG
        id: change-log 
        run: |
          tag=$(git tag --sort=-committerdate | head -1)
          prev=$(git tag --sort=-committerdate | head -2 | tail -1)
          log=$(git log ${prev}..${tag} --oneline)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "prev=$prev" >> $GITHUB_OUTPUT
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes in this Release:
              ${{ steps.change-log.outputs.log}}
          draft: true 

