# This will eventually become a composite action 
# that should shepherd code to and possibly from a client
name: RELEASER

on:
  push:
    tags:
      - '*.*.*' 

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          ref: development
          fetch-depth: 0
          persist-credentials: false
      
      - name: CHANGE_LOG
        id: change-log 
        uses: li-argonauts/gha-tag-parser@v0.4.0

      - name: ECHO THINGS
        run: |
          echo ${{github.ref}}
          echo ${{github.sha}}
          echo ${{steps.change-log.outputs.latest_tag}}
          echo ${{steps.change-log.outputs.prev_tag}}
          echo ${{steps.change-log.outputs.is_patch}}

      - name: Create Release
        if: ${{ steps.change-log.outputs.is_patch == 0}} 
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN}}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes in this Release:
              ${{ steps.change-log.outputs.compare_log}}
              
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{steps.tag-parser.outputs.prev_tag}}...${{steps.tag-parser.outputs.latest_tag}}
          draft: true 

